version: 2
jobs:
  build:
    docker:
      - image: kairosaero/dkr-circleci:production
    working_directory: /opt/kairos/build-home/repo
    steps:
      - checkout
      - run: kairos_container_init
      - run: kairos_python_dependencies
      - run: kairos_python_build
      - run: kairos_python_tests
      - run: kairos_python_package
      - run: kairos_python_deploy
      - run: kairos_lambda_publish
      - run: kairos_python_cleanup
      - store_artifacts:
          path: test-output
          destination: test-output
      - store_artifacts:
          path: dist
          destination: build-artifacts
      - store_test_results:
          path: test-output
notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
