version: 2
jobs:
  build:
    docker:
      - image: kairosaero/dkr-circleci:production
    working_directory: /opt/kairos/build-home/repo
    environment:
      registry: 137296740171.dkr.ecr.us-west-2.amazonaws.com
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t dkr-circleci .
      - run:
          name: push to docker registry
          command: |
            # login to ECR
            pip install -q awscli
            $(aws ecr get-login --no-include-email --region us-west-2)

            # apply appropriate tags and push
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              docker tag dkr-circleci:latest ${registry}/dkr-circleci:latest
            else
              docker tag dkr-circleci:latest ${registry}/dkr-circleci/${CIRCLE_BRANCH}:latest
              docker push ${registry}/dkr-circleci/${CIRCLE_BRANCH}:latest
            fi
notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
workflows:
  version: 2
  kairos-workflow:
    jobs:
      - build:
          context: org-global
