#!/bin/bash -e

# pipefail shell option means we still bail on error
set -o pipefail

. $(which kairos_env_init)
script_init # install error hooks


if [ -f requirements.txt ]; then
  echo "Installing dependencies from requirements.txt."
  echo " See logs/dependencies-install.log in artifacts for detailed output"
  mkdir -p dist
  # pipe to cat to suppress the status bars.
  pip install --log logs/dependencies-install.log -r requirements.txt | cat
else
  echo "WARNING: no requirements file found. (this is likely a bug)"
  exit 1
fi
