#!/bin/bash -e

. $(which kairos_env_init)
script_init # install error hooks

check_env () {
  if [ -z "${!1}" ]; then
    echo "No ${1} defined!" 1>&2
    exit 1
  fi
  return 0
}

if [ ! -z "${LAMBDA_NAME}" ]; then


  check_env LAMBDA_BUCKET
  check_env LAMBDA_PATH
  check_env LAMBDA_ROLE
  check_env LAMBDA_ZIP
  check_env LAMBDA_HANDLER

  # build lambda package
  echo "Building lambda package: dist/lambda.zip"
  mkdir lambda_build
  pip install -q --log logs/lamdba-requirements-install.log -t lambda_build -r requirements.txt
  pip install -q --log logs/lamdba-package-install.log -t lambda_build .
  (cd lambda_build && zip -r --quiet ../dist/lambda.zip .)

  echo "Pushing lambda packages to s3://${LAMBDA_BUCKET}/${LAMBDA_PATH}/"
  # push to S3 bucket to deploy lambda code
  aws s3 cp --only-show-errors dist/lambda.zip s3://${LAMBDA_BUCKET}/${LAMBDA_PATH}/${LAMBDA_ZIP}
  aws s3 cp --only-show-errors dist/lambda.zip s3://${LAMBDA_BUCKET}/${LAMBDA_PATH}/lambda-${CIRCLE_BUILD_NUM}.zip

  echo "Configuring lambda via AWS APIs"
  # create-or-update lambda function
  if ! aws lambda get-function --function-name $LAMBDA_NAME > /dev/null 2>&1 ; then
    error_exit 2 "You must create the lambda function via the console first."
  else
    aws lambda update-function-code --function-name ${LAMBDA_NAME} \
    --s3-bucket ${LAMBDA_BUCKET} --s3-key ${LAMBDA_PATH}/${LAMBDA_ZIP} \
    --publish
    aws lambda update-function-configuration --function-name ${LAMDA_NAME} \
      --description "${CIRCLE_PROJECT_REPONAME}#${CIRCLE_SHA1:0:7} (build ${CIRCLE_BUILD_NUM})"
  fi
  echo "Lambda publishing compelete"
else
  echo "No lamdba deployment defined. Skipping."
fi
