#!/bin/bash -e

. $(which kairos_env_init)

COVERAGE_OUTPUT=test-output/coverage
TEST_OUTPUT=test-output/nosetests

mkdir -p ${TEST_OUTPUT}
mkdir -p ${COVERAGE_OUTPUT}

python setup.py nosetests -s --cover-html --cover-html-dir $COVERAGE_OUTPUT

cp nosetests.xml $TEST_OUTPUT
