#!/bin/bash -e

. $(which kairos_env_init)
script_init # install error hooks

# enable multiprocessing - all cores
export NOSE_PROCESSES=-1

COVERAGE_OUTPUT=test-output/coverage
TEST_OUTPUT=test-output/nosetests

mkdir -p ${TEST_OUTPUT}
mkdir -p ${COVERAGE_OUTPUT}

python setup.py nosetests --cover-html --cover-html-dir $COVERAGE_OUTPUT

cp nosetests.xml $TEST_OUTPUT

# test for duplicate packages
pip freeze built-dependencies.txt

pip install kairos-buildlib

echo "Checking for duplicate packages in the upstream graph"
duplicate_package_check built-dependencies.txt
