#!/bin/bash

. $(which kairos_env_init)
script_init # install error hooks


if [ -f requirements.txt ]; then
  echo "Installing dependencies from requirements.txt."
  echo " See `dependencies-install.log` in artifacts for detailed output"
  mkdir -p dist
  pip install -q --log logs/dependencies-install.log -r requirements.txt
else
  echo "WARNING: no requirements file found. (this is likely a bug)"
  exit 1
fi
